# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: portainer/portainer-ce
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: ClusterIP
  httpPort: 9000
  httpNodePort:
  edgePort: 8000
  edgeNodePort:

ingress:
  enabled: true
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.0/24"
  ingressClassName: nginx
  tls:
    - hosts: 
        - portainer.andrewpjackson.com
      secretName: andrewpjackson.com-tls
  hosts:
    - host: portainer.andrewpjackson.com
      paths:
        - path: "/"
          pathType: Prefix

resources: {}

persistence:
  storageClass: "nfs-csi"
  size: "10Gi"
  annotations: {}