---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse
spec:
  storageClassName: "nfs-csi"
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany