apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  project: default
  source:
    path: ./helm/home-k8s/kustomize/code-server
    repoURL: https://github.com/Beyond-DevOps-Cloud/home-lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true