apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  project: default
  source:
    path: ./helm/home-k8s/kustomize/gitlab-runner
    repoURL: https://github.com/Beyond-DevOps-Cloud/home-lab.git
    targetRevision: HEAD
    # helm:
    #   # valueFiles:
    #   # - ./values.yaml
    #   parameters:
    #     - name: global.edition
    #       value: ce
    #     - name: upgradeCheck.enabled
    #       value: "false"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true