apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  project: default
  source:
    path: ./helm/home-k8s/kustomize/portainer
    repoURL: https://github.com/Beyond-DevOps-Cloud/home-lab.git
    targetRevision: HEAD
    plugin:
      name: argocd-lovely-plugin
      # env:
      #   - name: helm_args
      #     value: -f values.yaml
      #   - name: helm_dependency_name
      #     value: portainer
      #   - name: helm_dependency_repo
      #     value: 'https://portainer.github.io/k8s/'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true