apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: ./helm/home-k8s/kustomize/reflector
    repoURL: https://github.com/Beyond-DevOps-Cloud/home-lab.git
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true