apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rocketchat
  project: default
  source:
    path: ./helm/home-k8s/kustomize/rocketchat
    repoURL: https://github.com/Beyond-DevOps-Cloud/home-lab.git
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
      env:
        - name: helm_args
      env:
        - name: VALUES_FILE_PATH
          value: ./helm/home-k8s/values/rocketchat.yaml
        # - name: ARGOCD_ENV_HELM_VALUES
        #   value: |
        #     image.repository: registry.rocket.chat/rocketchat/rocket.chat
        #     host: chat.andrewpjackson.com
        #     mongodb.enabled: true
        #     mongodb.initdbScriptsConfigMap: rocketchat-mongodb-fix-clustermonitor-role-configmap
        #     mongodb.auth.rootPassword: rocketchat
        #     mongodb.auth.username: rocketchat
        #     mongodb.auth.password: rocketchat
        #     mongodb.auth.database: rocketchat
        #     mongodb.architecture: replicaset
        #     mongodb.replicaCount: 1
        #     mongodb.arbiter.enabled: false
        #     mongodb.arbiter.pdb.minAvailable: 0
        #     mongodb.pdb.minAvailable: 0
        #     mongodb.persistance.enabled: true
        #     mongodb.persistance.storageClass: "nfs-csi"
        #     mongodb.persistence.accessMode: ReadWriteOnce
        #     mongodb.persistence.size: 8Gi
        #     mongodb.volumePermissions: { enable: true }
        #     persistence.enabled: true
        #     persistence.storageClass: "nfs-csi"
        #     persistence.accessMode: ReadWriteOnce
        #     persistence.size: 8Gi
        #     ingress.enabled: true
        #     ingress.pathType: Prefix
        #     ingress.ingressClassName: "nginx"
        #     ingress.path: /
        #     ingress.tls[0].secretName: andrewpjackson.com-tls
        #     ingress.tls[0].hosts[0]: chat.andrewpjackson.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true