apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  ga.trackingid: 'UA-105170809-6'
  url: https://argocd.andrewpjackson.com
  configManagementPlugins: |-
    - name: argocd-lovely-plugin
      generate:
        command: ["argocd-lovely-plugin"]
    - name: argocd-vault-replacer
      generate:
        command: ["argocd-vault-replacer"]
    - name: kustomize-argocd-vault-replacer
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-replacer"]
    - name: helm-argocd-vault-replacer
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | argocd-vault-replacer"]
  # dex.config: |
  #   connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: fb563b3a8dd7ea52f683
  #       clientSecret: $dex.github.clientSecret
  #       orgs:
  #       - name: argoproj
  #         teams:
  #         - argo-cd-admins
  oidc.config: |
    name: Authentik
    issuer: https://authentik.andrewpjackson.com/application/o/argocd/
    clientID: $oidc.authentik.clientId
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups