apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
      - name: cmp
        command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
        image: kubectl-kustomize-helm # This can be off-the-shelf or custom-built image
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: cmp-plugin
          # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps 
          # mitigate path traversal attacks.
          - mountPath: /tmp
            name: cmp-tmp
      volumes:
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
        - emptyDir: {}
          name: cmp-tmp
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/argocd-flux-plugin
          name: custom-tools
          subPath: argocd-flux-plugin
      initContainers:
      - name: download-tools
        image: alexmt/argocd-flux:latest
        command: [sh, -c]
        args:
        - cp /usr/local/bin/argocd-flux-plugin /custom-tools/argocd-flux-plugin
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools