apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
          - mountPath: /helm-working-dir
            name: helm-working-dir
          env:
          - name: HELM_CACHE_HOME
            value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
          
        - name: cmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: gatsinski/kubectl-kustomize-helm # This can be off-the-shelf or custom-built image
          imagePullPolicy: IfNotPresent
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /helm-working-dir
              name: helm-working-dir
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-plugin
            - mountPath: /tmp
              name: cmp-tmp
          env:
          - name: HELM_CACHE_HOME
            value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
      volumes:
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
        - emptyDir: {}
          name: cmp-tmp
        - emptyDir: {}
          name: helm-working-dir