apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  ga.trackingid: 'UA-105170809-6'
  url: https://argocd.andrewpjackson.com
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE -f ($pwd)/values.yaml --include-crds . > all.yaml && kustomize build"]
  # dex.config: |
  #   connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: fb563b3a8dd7ea52f683
  #       clientSecret: $dex.github.clientSecret
  #       orgs:
  #       - name: argoproj
  #         teams:
  #         - argo-cd-admins
  oidc.config: |
    name: Authentik
    issuer: https://authentik.andrewpjackson.com/application/o/argocd/
    clientID: $oidc.authentik.clientId
    clientSecret: $oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups