apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  url: https://argocd.andrewpjackson.com
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.andrewpjackson.com/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  # dex.config: |
  #   # Setting staticClients allows Argo Workflows to use Argo CD's Dex installation for authentication
  #   staticClients:
  #     - id: argo-workflows-sso
  #       name: Argo Workflow
  #       redirectURIs:
  #         - https://workflows.andrewpjackson.com/oauth2/callback
  #       secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET