apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  
data:
  resource.exclusions: |
    - apiGroups:
      - "velero.io"
      kinds:
      - Backup
      clusters:
      - "*"
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  ga.trackingid: 'UA-105170809-6'
  url: https://argocd.andrewpjackson.com
  configManagementPlugins: |-
    - name: argocd-lovely-plugin
      generate:
        command: ["argocd-lovely-plugin"]
    - name: argocd-vault-replacer
      generate:
        command: ["argocd-vault-replacer"]
    - name: kustomize-argocd-vault-replacer
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-replacer"]
    - name: helm-argocd-vault-replacer
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | argocd-vault-replacer"]
  dex.config: |
      staticClients:
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - https://workflows.andrewpjackson.com/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      connectors:
      - config:
          issuer: https://authentik.andrewpjackson.com/application/o/argocd/
          redirectURI: https://argocd.andrewpjackson.com/api/dex/callback
          clientID: $dex.authentik.clientId
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups
        name: authentik
        type: oidc
        id: authentik
  # oidc.config: |
  #   name: Authentik
  #   issuer: https://authentik.andrewpjackson.com/application/o/argocd/
  #   clientID: $oidc.authentik.clientId
  #   clientSecret: $oidc.authentik.clientSecret
  #   requestedScopes:
  #     - openid
  #     - profile
  #     - email
  #     - groups