apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- base/namespace.yaml
- base/postgres/secrets.yaml
- base/postgres/statefulset.yaml
- base/postgres/svc-headless.yaml
- base/postgres/svc.yaml
- base/templates/common.yaml
- base/templates/configmap.yaml
- base/templates/ingress.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

# patchesStrategicMerge:
# - overlays/production/argo-cd-cm.yaml

namespace: vikunja