---
# Source: adguard-home/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adguard-home
  labels:
    helm.sh/chart: adguard-home-0.9.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.107.19"
    app.kubernetes.io/managed-by: Helm
