apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard.andrewpjackson.com
spec:
  secretName: adguard.andrewpjackson.com-tls
  issuerRef: 
    kind: ClusterIssuer
    name: wildcard-le-prod
  commonName: "*.adguard.andrewpjackson.com"
  dnsNames:
    - "*.adguard.andrewpjackson.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "adguard-home"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "adguard-home" # Control auto-reflection namespaces