apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andrewpjackson.com
spec:
  secretName: andrewpjackson.com-tls
  issuerRef: 
    kind: ClusterIssuer
    name: wildcard-le-prod
  commonName: "*.andrewpjackson.com"
  dnsNames:
    - "*.andrewpjackson.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "code-server,rocketchat,adguard-home,argocd,heimdall,bitwarden,portainer,searxng,dendrite,ocis,onedev,authentik,default"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "code-server,rocketchat,adguard-home,argocd,heimdall,bitwarden,portainer,searxng,dendrite,ocis,onedev,authentik,default" # Control auto-reflection namespaces