kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onedev-clusterrole
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "create"]