---
apiVersion: v1
kind: Secret
metadata:
  name: dendrite-key
type: Opaque
data:
  # how to generate: base64 encode a random string (reasonable long and mixed characters)
  # example generation command: `tr -cd '[:alnum:],.' < /dev/urandom | fold -w 50 | head -n 1 | base64`
  dendrite-key: LS0tLS1CRUdJTiBNQVRSSVggUFJJVkFURSBLRVktLS0tLQpLZXktSUQ6IGVkMjU1MTk6UFB2d0VPCgpQUHZ3RU9IM1BEZnZsWmFpMzJZRVZBb0N6c0RzcklwckxrYmZwdUlsZTJZPQotLS0tLUVORCBNQVRSSVggUFJJVkFURSBLRVktLS0tLQ==
