# version: v3.4.0

# context defines the context of this Desired State File.
# It is used to allow Helmsman identify which releases are managed by which DSF.
# Therefore, it is important that each DSF uses a unique context.
context: "home-k3s-lab" # defaults to "default" if not provided

# metadata -- add as many key/value pairs as you want
metadata:
  maintainer: "lordmuffin (dorkmeisterx69@gmail.com)"
  description: "This is used for my home-k3s-lab"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certificate
# certificates:
#caClient: "gs://mybucket/client.crt" # GCS bucket path
#caCrt: "s3://mybucket/ca.crt" # S3 bucket path
#caKey: "../ca.key" # valid local file relative path

settings:
  kubeContext: "home-k3s-lab" # will try connect to this context first, if it does not exist, it will be created using the details below
  # username: "admin"
  # password: "$K8S_PASSWORD" # the name of an environment variable containing the k8s password
  #clusterURI: "$SET_URI" # the name of an environment variable containing the cluster API
  #clusterURI: "https://192.168.99.100:8443" # equivalent to the above
  #storageBackend: "secret"
  #slackWebhook:  "$slack" # or your slack webhook url
  reverseDelete: true # reverse the priorities on delete
  #### to use bearer token:
  #  bearerToken: true
  #  clusterURI: "https://kubernetes.default"
  # globalHooks:
  #   successCondition: "Initialized"
  #   deleteOnSuccess: true
  #   postInstall: "job.yaml"
  globalMaxHistory: 10

# define your environments and their k8s namespaces
namespaces:
  default:
    protected: false
  keda:
    protected: false
  metallb-system:
    protected: false
  cert-manager:
    protected: false
  ingress-nginx:
    protected: false
  authentik:
    protected: false
  bitwarden:
    protected: false
  onedev:
    protected: false
  searxng:
    protected: false
  uptime-kuma:
    protected: false
  ocis:
    protected: false
  matrix:
    protected: false
  dendrite:
    protected: false
  synapse:
    protected: false
  portainer:
    protected: false
  heimdall:
    protected: false
# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name: "repo_url"
# only private repos hosted in s3 buckets are now supported
helmRepos:
  csi-driver-nfs: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
  emberstack: "https://emberstack.github.io/helm-charts"
  metallb: "https://metallb.github.io/metallb"
  jetstack: "https://charts.jetstack.io"
  ingress-nginx: "https://kubernetes.github.io/ingress-nginx"
  kedacore: "https://kedacore.github.io/charts"
  argo: "https://argoproj.github.io/argo-helm"

  authentik: "https://charts.goauthentik.io"
  home-lab-charts: "https://raw.githubusercontent.com/lordmuffin/home-lab-charts/repo"
  onedev: "https://dl.cloudsmith.io/public/onedev/onedev/helm/charts"
  searxng: "https://charts.searxng.org"
  halkeye: "https://halkeye.github.io/helm-charts/"
  k8s-at-home: "https://k8s-at-home.com/charts/"
  portainer: "https://portainer.github.io/k8s/"

  #myS3repo: "s3://my-S3-private-repo/charts"
  #myGCSrepo: "gs://my-GCS-private-repo/charts"
  #custom:  "https://$user:$pass@mycustomrepo.org"

# define the desired state of your applications helm charts
# each contains the following:

apps:
  csi-driver-nfs:
    enabled: true
    chart: csi-driver-nfs/csi-driver-nfs
    namespace: kube-system
    version: "4.1.0"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  reflector:
    enabled: true
    chart: emberstack/reflector
    namespace: kube-system
    version: "6.1.47"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  nfs-config:
    namespace: "kube-system" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "./charts/nfs-config" # changing the chart name means delete and recreate this chart
    version: "0.0.2" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  metallb:
    enabled: true
    chart: metallb/metallb
    namespace: metallb-system
    version: "0.13.7"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -10
  metallb-config:
    enabled: true # change to false if you want to delete this app release empty: false:
    namespace: metallb-system # maps to the namespace as defined in namespaces above
    chart: "./charts/metallb-config" # changing the chart name means delete and recreate this chart
    version: "0.0.10" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    wait: true
    priority: -9
  ingress-nginx:
    enabled: true # change to false if you want to delete this app release empty: false:
    namespace: ingress-nginx # maps to the namespace as defined in namespaces above
    chart: "ingress-nginx/ingress-nginx" # changing the chart name means delete and recreate this chart
    version: "4.4.0" # chart version
    ### Optional values below
    valuesFile: "values/nginx.yaml" # leaving it empty uses the default chart values
      # "controller.nginxDebug": "true"
    # setFile: "./files/nginx-setfile.yaml"
    test: false
    protected: false
    wait: true
    priority: -9
  kedacore:
    enabled: false
    chart: kedacore/keda
    namespace: keda
    version: "2.9.1"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  cert-manager:
    enabled: true
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.10.1
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -10
    hooks:
      preInstall: "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml"
      postInstall: "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml"
  general-config:
    enabled: true
    chart: "./charts/general-config"
    namespace: cert-manager
    version: "0.0.7"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -9
  authentik:
    namespace: "authentik" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "authentik/authentik" # changing the chart name means delete and recreate this chart
    version: "2022.11.3" # chart version
    ### Optional values below
    valuesFile: "values/authentik.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -9
  argo-workflows:
    namespace: "argo" # maps to the namespace as defined in namespaces above
    enabled: false # change to false if you want to delete this app release empty: false:
    chart: "argo/argo-workflows" # changing the chart name means delete and recreate this chart
    version: "0.22.4" # chart version
    ### Optional values below
    valuesFile: "values/argo-workflows.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -8
    hooks:
      preInstall: "files/argo-secrets.yaml"
      preUpgrade: "files/argo-secrets.yaml"
      preDelete: "files/argo-secrets.yaml"
  argo-cd:
    namespace: "argo" # maps to the namespace as defined in namespaces above
    enabled: false # change to false if you want to delete this app release empty: false:
    chart: "argo/argo-cd" # changing the chart name means delete and recreate this chart
    version: "5.16.11" # chart version
    ### Optional values below
    valuesFile: "values/argo-cd.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -8
    hooks:
      preInstall: "files/argo-secrets.yaml"
      preUpgrade: "files/argo-secrets.yaml"
      preDelete: "files/argo-secrets.yaml"

  bitwarden:
    namespace: "bitwarden" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "./charts/bitwarden" # changing the chart name means delete and recreate this chart
    version: "0.1.6" # chart version
    ### Optional values below
    valuesFile: "values/bitwarden_rs.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -5
  example:
    namespace: "default" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "./charts/example" # changing the chart name means delete and recreate this chart
    version: "0.1.9" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  onedev:
    namespace: "onedev" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "onedev/onedev" # changing the chart name means delete and recreate this chart
    version: "7.7.14" # chart version
    ### Optional values below
    valuesFile: "values/onedev.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  searxng:
    namespace: "searxng" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "searxng/searxng" # changing the chart name means delete and recreate this chart
    version: "1.0.0" # chart version
    ### Optional values below
    valuesFile: "values/searxng.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  ocis:
    namespace: "ocis" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "./charts/ocis" # changing the chart name means delete and recreate this chart
    version: "0.1.0" # chart version
    ### Optional values below
    valuesFile: "values/ocis.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
    hooks:
      postInstall: "files/ocis-secrets.yaml"
      postInstall: "files/ocis-config.yaml"
      postInstall: "files/ocis-external-user-mgmt-secrets.yaml"
      postUpgrade: "files/ocis-secrets.yaml"
      postUpgrade: "files/ocis-config.yaml"
      postUpgrade: "files/ocis-external-user-mgmt-secrets.yaml"
      postDelete: "files/ocis-secrets.yaml"
      postDelete: "files/ocis-config.yaml"
      postDelete: "files/ocis-external-user-mgmt-secrets.yaml"
  synapse:
    enabled: true
    chart: "./charts/synapse"
    namespace: synapse
    version: "0.0.1"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  matrix:
    enabled: false
    chart: "halkeye/synapse"
    namespace: matrix
    version: "0.8.23"
    ### Optional values below
    valuesFile: "values/matrix.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  portainer:
    namespace: "portainer" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "portainer/portainer" # changing the chart name means delete and recreate this chart
    version: "1.0.38" # chart version
    ### Optional values below
    valuesFile: "values/portainer.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  # dendrite:
  #   enabled: true
  #   chart: "k8s-at-home/dendrite"
  #   namespace: dendrite
  #   version: "6.3.1"
  #   ### Optional values below
  #   valuesFile: "values/dendrite.yaml" # leaving it empty uses the default chart values
  #   test: false
  #   protected: false
  #   priority: 0
  #   hooks:
  #     postInstall: "files/dendrite-secrets.yaml"
  #     postUpgrade: "files/dendrite-secrets.yaml"
  #     postDelete:  "files/dendrite-secrets.yaml"
  # grocy:
  #   namespace: "default" # maps to the namespace as defined in namespaces above
  #   enabled: true # change to false if you want to delete this app release empty: false:
  #   chart: "home-lab-charts/grocy" # changing the chart name means delete and recreate this chart
  #   version: "0.1.3" # chart version
  #   ### Optional values below
  #   valuesFile: "./values/grocy.yaml" # leaving it empty uses the default chart values
  #   test: false
  #   protected: false
  #   priority: -1

# See https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps for more apps options