# version: v3.4.0

# context defines the context of this Desired State File.
# It is used to allow Helmsman identify which releases are managed by which DSF.
# Therefore, it is important that each DSF uses a unique context.
context: "home-k3s-lab" # defaults to "default" if not provided

# metadata -- add as many key/value pairs as you want
metadata:
  maintainer: "lordmuffin (dorkmeisterx69@gmail.com)"
  description: "This is used for my home-k3s-lab"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certificate
# certificates:
#caClient: "gs://mybucket/client.crt" # GCS bucket path
#caCrt: "s3://mybucket/ca.crt" # S3 bucket path
#caKey: "../ca.key" # valid local file relative path

settings:
  kubeContext: "home-k3s-lab" # will try connect to this context first, if it does not exist, it will be created using the details below
  # username: "admin"
  # password: "$K8S_PASSWORD" # the name of an environment variable containing the k8s password
  #clusterURI: "$SET_URI" # the name of an environment variable containing the cluster API
  #clusterURI: "https://192.168.99.100:8443" # equivalent to the above
  #storageBackend: "secret"
  #slackWebhook:  "$slack" # or your slack webhook url
  #reverseDelete: false # reverse the priorities on delete
  #### to use bearer token:
  #  bearerToken: true
  #  clusterURI: "https://kubernetes.default"
  # globalHooks:
  #   successCondition: "Initialized"
  #   deleteOnSuccess: true
  #   postInstall: "job.yaml"
  globalMaxHistory: 10

# define your environments and their k8s namespaces
namespaces:
  default:
    protected: false
  metallb-system:
    protected: false
  cert-manager:
    protected: false
  nginx-ingress:
    protected: false
  tekton:
    protected: false
  cattle-system:
    protected: false
  onedev:
    protected: false
    
# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name: "repo_url"
# only private repos hosted in s3 buckets are now supported
helmRepos:
  csi-driver-nfs: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
  metallb: "https://metallb.github.io/metallb"
  jetstack: "https://charts.jetstack.io"
  nginx-stable: "https://helm.nginx.com/stable"
  home-lab-charts: "https://raw.githubusercontent.com/lordmuffin/home-lab-charts/repo"
  onedev: "https://dl.cloudsmith.io/public/onedev/onedev/helm/charts"

  #myS3repo: "s3://my-S3-private-repo/charts"
  #myGCSrepo: "gs://my-GCS-private-repo/charts"
  #custom:  "https://$user:$pass@mycustomrepo.org"

# define the desired state of your applications helm charts
# each contains the following:

apps:
  csi-driver-nfs:
    enabled: true
    chart: csi-driver-nfs/csi-driver-nfs
    namespace: kube-system
    version: "4.1.0"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  nfs-config:
    namespace: "kube-system" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "home-lab-charts/nfs-config" # changing the chart name means delete and recreate this chart
    version: "0.0.2" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -11
  metallb:
    enabled: true
    chart: metallb/metallb
    namespace: metallb-system
    version: "0.13.7"
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -10
  metallb-config:
    enabled: true # change to false if you want to delete this app release empty: false:
    namespace: metallb-system # maps to the namespace as defined in namespaces above
    chart: "home-lab-charts/metallb-config" # changing the chart name means delete and recreate this chart
    version: "0.0.10" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    wait: true
    priority: -9
  nginx-ingress:
    enabled: true # change to false if you want to delete this app release empty: false:
    namespace: nginx-ingress # maps to the namespace as defined in namespaces above
    chart: "nginx-stable/nginx-ingress" # changing the chart name means delete and recreate this chart
    version: "0.15.2" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    setString: 
      "controller.kind": "daemonset"
      # "controller.nginxDebug": "true"
    # setFile: "./files/nginx-setfile.yaml"
    test: false
    protected: false
    wait: true
    priority: -9
  cert-manager:
    enabled: true
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.10.1
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -10
    hooks:
      preInstall: "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml"
      postInstall: "https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.crds.yaml"
  tekton-pipelines:
    namespace: "tekton" # maps to the namespace as defined in namespaces above
    enabled: false # change to false if you want to delete this app release empty: false:
    chart: "home-lab-charts/tekton-pipelines" # changing the chart name means delete and recreate this chart
    version: "0.0.1" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: -8
  example:
    namespace: "default" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "home-lab-charts/example" # changing the chart name means delete and recreate this chart
    version: "0.1.9" # chart version
    ### Optional values below
    valuesFile: "" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  onedev:
    namespace: "onedev" # maps to the namespace as defined in namespaces above
    enabled: true # change to false if you want to delete this app release empty: false:
    chart: "onedev/onedev" # changing the chart name means delete and recreate this chart
    version: "7.7.14" # chart version
    ### Optional values below
    valuesFile: "values/onedev.yaml" # leaving it empty uses the default chart values
    test: false
    protected: false
    priority: 0
  # grocy:
  #   namespace: "default" # maps to the namespace as defined in namespaces above
  #   enabled: true # change to false if you want to delete this app release empty: false:
  #   chart: "home-lab-charts/grocy" # changing the chart name means delete and recreate this chart
  #   version: "0.1.3" # chart version
  #   ### Optional values below
  #   valuesFile: "./values/grocy.yaml" # leaving it empty uses the default chart values
  #   test: false
  #   protected: false
  #   priority: -1

# See https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps for more apps options