apiVersion: v1
kind: PersistentVolume
metadata:
   name: synapse-pv
   labels:
     pvc_type: synapse-pv
     type: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
   - ReadWriteOnce
  storageClassName: "nfs-csi"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/SSD/k3s-pvc/synapse
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-csi"
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pvc_type:  synapse-pv