apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "6.10.0" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    values:
      global:
        edition: ce
        hosts:
          domain: andrewpjackson.com # use a real domain here
        ingress:
          enabled: true
          class: nginx
          configureCertmanager: false
          tls:
            enabled: true
            secretName: andrewpjackson.com-tls
        certmanager-issuer:
          email: dorkmeisterx69@gmail.com # use your real email address here
        appConfig:
          omniauth:
            enabled: true
            # autoSignInWithProvider: ['openid_connect']
            syncProfileFromProvider: ['openid_connect']
            syncProfileAttributes: ['email']
            allowSingleSignOn: ['openid_connect']
            blockAutoCreatedUsers: false
            autoLinkLdapUser: false
            autoLinkoidcUser: true
            autoLinkUser: ['openid_connect']
            externalProviders: []
            allowBypassTwoFactor: []
            providers:
              - secret: gitlab-authentik-oidc
                key: provider