apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "15.10.0" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    values:
      global:
        hosts:
          domain: gitlab.andrewpjackson.com # use a real domain here
        ingress:
          configureCertmanager: false
        nginx-ingress:
          enabled: true
      certmanager-issuer:
        email: dorkmeisterx69@gmail.com # use your real email address here