apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- base/rbac.yaml
- base/cr.yaml
# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

# patchesStrategicMerge:
# - overlays/production/argo-cd-cm.yaml

namespace: vault