apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
# - base/argo-cd-issuer.yaml
# - base/argo-cd-certificate.yaml
- ./base
- base/argo-cd-ui-ingress.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- base/cmp-plugin.yaml

patchesStrategicMerge:
# - overlays/production/argocd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml
# - overlays/production/argocd-notifications-controller-deploy.yaml
# - overlays/production/argocd-notifications-cm.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml
- secrets/argo-secrets.yaml
- overlays/production/argo-cd-rbac-cm.yaml
- overlays/production/cmp-plugin.yaml


patches:
- path: overlays/production/argo-dex-deploy.yaml
  target:
    kind: Deployment
    name: argocd-dex-server

- path: overlays/production/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: overlays/production/argocd-lovely-plugin.yaml
  target:
    kind: Deployment
    name: argocd-repo-server
- path: overlays/production/argocd-vault-replacer.yaml
  target:
      kind: Deployment
      name: argocd-repo-server
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    kind: Deployment
    name: argocd-server-deploy-command

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argo-cd/argocd
  newTag: 2.6.0-323f8fdf
