## Deploy Homepage and HomepageSC with a shared config volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      serviceAccountName: homepage-discovery
      containers:
        - name: homepage
          image: 'ghcr.io/benphelps/homepage:latest'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/config" # Mount the shared config directory
              name: shared-data
        - name: homepagesc
          image: 'ghcr.io/uatec/homepagesc:latest'
          volumeMounts:
            - mountPath: "/app/config" # Mount the shared config directory
              name: shared-data
          env:
            - name: OUTPUTLOCATION # Tell HomepageSC to output services in to the shared directory
              value: "/app/config/services.yaml"
            - name: INCLUSTER # Use kubeconfig provided by the cluster itself
              value: "true"


# Grant HomepageSC permission to discover ingresses and widget secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-discovery
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: homepage-discovery
  namespace: homepage