apiVersion: v1
kind: Namespace
metadata:
  name: homepage
  labels:
    app.kubernetes.io/instance: default
  #   app.kubernetes.io/part-of: tekton-pipelines
  #   pod-security.kubernetes.io/enforce: baseline