apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- base/andrewpjackson.com-wildcard.yaml
- base/onedevclusterrole.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

# patchesStrategicMerge:
# - overlays/production/argo-cd-cm.yaml

namespace: cert-manager
