---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sd-k8s-pvc
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.10
  share: /mnt/SpinningDisks/Kubernetes-PVC
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1