---
# Source: vikunja/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: vikunja
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/version: 0.17.0
    helm.sh/chart: vikunja-6.1.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/instance: release-name
---
# Source: vikunja/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/version: 0.17.0
    helm.sh/chart: vikunja-6.1.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vikunja
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vikunja
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: vikunja
          image: "caddy:2.4.2-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: vikunja-config
              mountPath: /etc/vikunja/config.yml
              subPath: Vikunja.yaml
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
        - env: []
          image: vikunja/api:0.17.1
          imagePullPolicy: IfNotPresent
          name: api
          volumeMounts:
          - mountPath: /etc/vikunja/config.yml
            name: vikunja-config
            subPath: Vikunja.yaml
        - image: vikunja/frontend:0.17.0
          imagePullPolicy: IfNotPresent
          name: frontend
      volumes:
        - name: caddy-config
          configMap:
            name: vikunja-config
        - name: vikunja-config
          configMap:
            name: vikunja-config
