---
# Source: vikunja/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  labels:
    helm.sh/chart: vikunja-6.1.2
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.17.0"
    app.kubernetes.io/managed-by: Helm
data:
  Caddyfile: |-
    {
      admin off
    }

    :8080 {
        log {
            output stdout
        }

        @api {
            path /api/*
            path /.well-known/*
            path /dav/*
        }

        header {
            # Remove Server header
            -Server
        }

        # API
        handle @api {
            reverse_proxy localhost:3456
        }

        # Filtron
        handle {
            reverse_proxy localhost:80
        }
    }
  Vikunja.yaml: |-
    service:
      jwtsecret: "myVeryComplexJWTSecret"
    auth:
      # Local authentication will let users log in and register (if enabled) through the db.
      # This is the default auth mechanism and does not require any additional configuration.
      local:
        # Enable or disable local authentication
        enabled: true
      # OpenID configuration will allow users to authenticate through a third-party OpenID Connect compatible provider.<br/>
      # The provider needs to support the `openid`, `profile` and `email` scopes.<br/>
      # **Note:** Some openid providers (like gitlab) only make the email of the user available through openid claims if they have set it to be publicly visible.
      # If the email is not public in those cases, authenticating will fail.
      # **Note 2:** The frontend expects to be redirected after authentication by the third party
      # to <frontend-url>/auth/openid/<auth key>. Please make sure to configure the redirect url with your third party
      # auth service accordingly if you're using the default Vikunja frontend.
      # Take a look at the [default config file](https://github.com/go-vikunja/api/blob/main/config.yml.sample) for more information about how to configure openid authentication.
      openid:
        # Enable or disable OpenID Connect authentication
        enabled: true
        # A list of enabled providers
        providers:
          # The name of the provider as it will appear in the frontend.
          - name: "authentik"
            # The auth url to send users to if they want to authenticate using OpenID Connect.
            redirecturl: https://vikunja.andrewpjackson.com/auth/openid/
            authurl: https://authentik.andrewpjackson.com/application/o/vikunja/
            # The client ID used to authenticate Vikunja at the OpenID Connect provider.
            clientid: ffc44987206f0dab24563ed530fb3a4f22a19f0e
            # The client secret used to authenticate Vikunja at the OpenID Connect provider.
            clientsecret: ea0667c3efe5c96491f277f1b5fd92d9aa286244eda2c44bcc0372b827e4ee9b8cc131ce6a49c9d8aae1ea9b98a3a74540300dfef272f6292768d53cc9687b36
