---
# Source: vikunja/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  labels:
    helm.sh/chart: vikunja-6.1.2
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.17.0"
    app.kubernetes.io/managed-by: Helm
data:
  Caddyfile: |-
    {
      admin off
    }

    :8080 {
        log {
            output stdout
        }

        @api {
            path /api/*
            path /.well-known/*
            path /dav/*
        }

        header {
            # Remove Server header
            -Server
        }

        # API
        handle @api {
            reverse_proxy localhost:3456
        }

        # Filtron
        handle {
            reverse_proxy localhost:80
        }
    }
  Vikunja.yaml: |-
    service:
      jwtsecret: "myVeryComplexJWTSecret"
