{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bitwarden-k8s.fullname" . -}}
{{- $ingressApiIsStable := eq (include "bitwarden-k8s.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "bitwarden-k8s.ingress.supportsIngressClassName" .) "true" -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType  := .Values.ingress.pathType -}}
{{- $ingressClassName  := .Values.ingress.ingressClassName -}}

apiVersion: {{ include "bitwarden-k8s.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bitwarden-k8s.name" . }}
    helm.sh/chart: {{ include "bitwarden-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $ingressClassName }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
{{- end }}