apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:

# - base/nfs-csi.yaml
# - base/nfs-sd-k8s-pvc.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

# patchesStrategicMerge:
# - overlays/production/argo-cd-cm.yaml

namespace: kube-system
