apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql-db-ha.my-keycloak-operator.svc.cluster.local
    usernameSecret:
      name: keycloak-postgresql-db-pguser-keycloak
      key: user
    passwordSecret:
      name: keycloak-postgresql-db-pguser-keycloak
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: keycloak.andrewpjackson.com
    admin: keycloak-admin.andrewpjackson.com
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false