apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql-db
    usernameSecret:
      name: keycloak-postgresql-db-pguser-keycloak-postgresql-db
      key: username
    passwordSecret:
      name: keycloak-postgresql-db-pguser-keycloak-postgresql-db
      key: password
  http:
    tlsSecret: andrewpjackson.com-tls
  hostname:
    hostname: keycloak.andrewpjackson.com
  ingress:
    enabled: true