apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  instances: 1
  hostname: keycloak.andrewpjackson.com
  tlsSecret: andrewpjackson.com-tls
