apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloak-postgresql-db
spec:
  users:
    - name: keycloak
      databases:
        - keycloak
      options: "SUPERUSER"
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.2-0
  postgresVersion: 15
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-sd-k8s-pvc
        # podAntiAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #   - weight: 1
        #     podAffinityTerm:
        #       topologyKey: kubernetes.io/hostname
        #       labelSelector:
        #         matchLabels:
        #           postgres-operator.crunchydata.com/cluster: keycloakdb
        #           postgres-operator.crunchydata.com/instance-set: "00"
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql-db
spec:
  selector:
    app: keycloak-postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432