apiVersion: v1
kind: Secret
metadata:
  name: gitlab-authentik-saml
type: Opaque
data:
  provider: bmFtZTogc2FtbApsYWJlbDogJ2F1dGhlbnRpaycKYXJnczoKICBhc3NlcnRpb25fY29uc3VtZXJfc2VydmljZV91cmw6ICdodHRwczovL2dpdGxhYi5hbmRyZXdwamFja3Nvbi5jb20vdXNlcnMvYXV0aC9zYW1sL2NhbGxiYWNrJwogIGlkcF9jZXJ0X2ZpbmdlcnByaW50OiAnMDY6YjA6ZDk6MDM6MzI6N2U6ZjY6MDM6MmI6ZmI6Mzc6OGI6MGQ6NjI6ODI6MTg6ZjA6NDE6OTI6MDYnCiAgaWRwX3Nzb190YXJnZXRfdXJsOiAnaHR0cHM6Ly9hdXRoZW50aWsuYW5kcmV3cGphY2tzb24uY29tL2FwcGxpY2F0aW9uL3NhbWwvZ2l0bGFiL3Nzby9iaW5kaW5nL3JlZGlyZWN0LycKICBpc3N1ZXI6ICdodHRwczovL2dpdGxhYi5hbmRyZXdwamFja3Nvbi5jb20nCiAgbmFtZV9pZGVudGlmaWVyX2Zvcm1hdDogJ3VybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1laWQtZm9ybWF0OmVtYWlsQWRkcmVzcyc=