apiVersion: v1
kind: Secret
metadata:
  name: gitlab-authentik-saml
type: Opaque
data:
  provider.yaml: 
    name: saml
    label: 'authentik'
    args:
      assertion_consumer_service_url: 'https://gitlab.andrewpjackson.com/users/auth/saml/callback'
      idp_cert_fingerprint: '06:b0:d9:03:32:7e:f6:03:2b:fb:37:8b:0d:62:82:18:f0:41:92:06'
      idp_sso_target_url: 'https://authentik.andrewpjackson.com/application/saml/gitlab/sso/binding/redirect/'
      issuer: 'https://gitlab.andrewpjackson.com'
      name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'