apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  annotations:
    workflows.argoproj.io/rbac-rule: "'ArgoCD Admins' in groups && email == 'dorkmeisterx69@gmail.com'"
    workflows.argoproj.io/rbac-rule-precedence: "1"