apiVersion: v1
# data:
  # oidc.config: |
  #   name: Authentik
  #   issuer: https://authentik.andrewpjackson.com/application/o/argocd/
  #   clientID: $oidc.authentik.clientId
  #   clientSecret: $oidc.authentik.clientSecret
  #   requestedScopes:
  #     - openid
  #     - profile
  #     - email
  #     - groups
  # # https://github.com/settings/applications/1416526
data:
  dex.config: |
      connectors:
      - config:
          issuer: https://authentik.andrewpjackson.com/application/o/argocd/
          clientID: $dex.authentik.clientId
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups
        name: authentik
        type: oidc
        id: authentik
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
