apiVersion: v1
# data:
  # oidc.config: |
  #   name: Authentik
  #   issuer: https://authentik.andrewpjackson.com/application/o/argocd/
  #   clientID: $oidc.authentik.clientId
  #   clientSecret: $oidc.authentik.clientSecret
  #   requestedScopes:
  #     - openid
  #     - profile
  #     - email
  #     - groups
  # # https://github.com/settings/applications/1416526
data:
  sso: |
    # This is the root URL of the OIDC provider (required).
    issuer: https://authentik.andrewpjackson.com/application/o/argo-workflows/
    # This is name of the secret and the key in it that contain OIDC client
    # ID issued to the application by the provider (required).
    clientId:
      name: argo-workflows-sso
      key: client-id
    # This is name of the secret and the key in it that contain OIDC client
    # secret issued to the application by the provider (required).
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    # This is the redirect URL supplied to the provider (required). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible.
    redirectUrl: https://workflows.andrewpjackson.com/oauth2/callback
    # Additional scopes to request. Typically needed for SSO RBAC. >= v2.12
    scopes:
     - groups
     - email
    # RBAC Config. >= v2.12
    rbac:
      enabled: true
    # Skip TLS verify, not recommended in production environments. Useful for testing purposes. >= v3.2.4
    insecureSkipVerify: false
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
