apiVersion: v1
data:
  # https://github.com/settings/applications/1416526
  config: |
    sso:
      issuer: https://authentik.andrewpjackson.com/application/o/argocd/
      clientId:
        name: argocd-secret
        key: oidc.authentik.clientId
      clientSecret:
        name: argocd-secret
        key: oidc.authentik.clientSecret
      redirectUrl: https://workflows.andrewpjackson.com/oauth2/callback
      scopes:
        - openid
        - profile
        - email
        - groups
      rbac:
        enabled: false
    workflowDefaults:
      spec:
        activeDeadlineSeconds: 600
    retentionPolicy:
      completed: 20
      failed: 3
      errored: 3
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
