apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://gitlab.com/api/v4/projects/18899486/packages/generic/gitlab-operator/0.18.0/gitlab-operator-kubernetes-0.18.0.yaml
- base/gitlab.yaml

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              key: "kubernetes.io/hostname=k3s-agent-001"
    target:
      kind: (StatefulSet|Deployment|Job|Pods)