namespace: tekton-pipelines
resources:
- pipeline.yaml
- pipelinerun.yaml
- task.yaml
- secret.yaml
- serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    tekton.dev/git-0: https://github.com
# secretGenerator:
# - literals:
#   - known_hosts=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcN7h0FDM8rF71CNtXagxjQMQUkWjFbHPel4jFofwejsJv5S98QBYdjuLpAlFQUR/KfYqRmjPghRbKZWlhX8Vlsiji8+id+yGSLd7MmLICGfHlRsEVsQWnWQ8T/5K01jl9koBQox6H+rjoM1mRoEPN0ZdQvCXDsxRHal+JP8G4NKx7ZDj1XCqhTj1dvoShWy+ZEvE7voAd8CTVHPtZo+8EphsEm9m8e8j5XmVULJdcHeNY470N4A9t4etn2/WuTbVy1/iQc388e+zlTY2ZECY+yGNxFEav5DfhKDABqj1belfOzGiU8Ct0NJyS+88vDfeoPlX9umUOmG89YfvyQmrReqJLn7i3+ZWZjz6ISA392wniBuU7ciOkyJddVWQXsRYLrsh9o5x7ZdADUZmBhH7gn1EwOYVmwpsbRlEDgObERhYR9gGzI0eTyhbk6Hb85SdXHGoV/N4GgVS45+duvo8vMCZyucEKUoQESsc37l62z0wCGNN94S+peG4bYzgh2uFs7DqTp8d48Jvmy5BLW4E5kEhG20m/aG6jm+Lw85NMvYKDUjxRtr7HNbAm5Z3LVcV34UooH9rc6C/cK8YTpy/yKkYwOPvQKBFAVCNwrp/XXbRLMmFqtFYmnoYrdXrh/x/DCB9MwAi/SB1TbhQ7T+5CjHWO1LoV2NaI4CVi0lOxxw== dorkmeisterx69@gmail.com
#   - id_rsa=-----BEGIN OPENSSH PRIVATE KEY-----
#       b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCQhuJoei
#       ZzTusMeWnvI2QYAAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDcN7h0FDM8
#       rF71CNtXagxjQMQUkWjFbHPel4jFofwejsJv5S98QBYdjuLpAlFQUR/KfYqRmjPghRbKZW
#       lhX8Vlsiji8+id+yGSLd7MmLICGfHlRsEVsQWnWQ8T/5K01jl9koBQox6H+rjoM1mRoEPN
#       0ZdQvCXDsxRHal+JP8G4NKx7ZDj1XCqhTj1dvoShWy+ZEvE7voAd8CTVHPtZo+8EphsEm9
#       m8e8j5XmVULJdcHeNY470N4A9t4etn2/WuTbVy1/iQc388e+zlTY2ZECY+yGNxFEav5Dfh
#       KDABqj1belfOzGiU8Ct0NJyS+88vDfeoPlX9umUOmG89YfvyQmrReqJLn7i3+ZWZjz6ISA
#       392wniBuU7ciOkyJddVWQXsRYLrsh9o5x7ZdADUZmBhH7gn1EwOYVmwpsbRlEDgObERhYR
#       9gGzI0eTyhbk6Hb85SdXHGoV/N4GgVS45+duvo8vMCZyucEKUoQESsc37l62z0wCGNN94S
#       +peG4bYzgh2uFs7DqTp8d48Jvmy5BLW4E5kEhG20m/aG6jm+Lw85NMvYKDUjxRtr7HNbAm
#       5Z3LVcV34UooH9rc6C/cK8YTpy/yKkYwOPvQKBFAVCNwrp/XXbRLMmFqtFYmnoYrdXrh/x
#       /DCB9MwAi/SB1TbhQ7T+5CjHWO1LoV2NaI4CVi0lOxxwAAB1B9MkyfTvKb9jiGnKIYKVgu
#       WbSTIMOq5LOoTtsgw8AqaOhg1Cyhi+X1+4sM6Dp8hK9uHJJ9nQYcqEgDTGqeDNzF31hyiq
#       KzlZQdjYoS0oU7Rr82ur71lfeN4dStmv2mBsm+MQq6iYGjs1Z4QF5hUj9zxfk5pom7ybqO
#       LWKmJeeoqDx8O9G4F3F7oOAV047XE8MoS6IPsfLboDR3A+TS4qDHJ5YqtNaFJcM5jKpCar
#       lT3LZHh1fgiwwJZB7tGtHEJyd7l9PeWaTGNgEUbgNcMr3uY0ZxlZraiYJ/ddoZFUMRHT8A
#       FO+MzXvBYY9gE0uwY/79JclALZZvRAXL+UzDGSAoN3J7mkCnmIeutQ8+A7sI+d0knKWx15
#       FUBLkmj0ZNK3ZYlCzeB+pQfmD8/6Ixylj0aUnSwmALOox5NNoX7oJaH4kK7FdR7ywHbk2g
#       LRP0lXgV2hsZA47rbtsT0wFunIOuh6YkQOvcsLBlub7V4/CpZA7M988vf2Qqz3f3rLl8KV
#       1mlkPXH+zqJiROJDTRTB9hL6V6APUC5OymUE8FcPaeem6fcM2QCGkxf/+FWy7CmOkt0HH+
#       Y29gNRXTffXQUgyseL8Tvnm+7Gg3dBVd9M/msCWUN3JhJqwX+d7fsvCuLqA6sdGl29T3g4
#       WlRKXJsbp/vQjFg7AL1UxLN6e+hC8FxPWML2ww3T34QjaFFYRrAK47Yy7LV444y/hoYbD/
#       FRqGHM8yllhXh0fpTHmCDzKhrh8uE3Re3Fq0JiqYceK0AOCXgXQoDZaj/xslNLeYE5JAj6
#       NQ721nqLc9NcO/29mt8Eb6sO3PIQ7iACbxiCus2VKzscP+sPKIoSrRz77yC6LrIwmvS/ea
#       s63xtcGcoB0hB2xU69P9udn1l0D34qbHQW8ZoqRJJx3pp+2+hJCXV5eJQbxtLj64lU4dM5
#       KR8OfDB4Ii40ci88E029zgDt7+aYxeDdbQTKts2MH6jqUxX1Frr5rvphAn2tTLJnx96WGc
#       PvnsGsMKNT4Fhr3ltepQB1H18TLNHzhsyR+XcBVhkOguSqd1xo36U7mOfjvbVNH0bfYAzd
#       cPJkBeNkeL3dmW0Er2arrGr1K+KisJJ02fU2FZQjVHW6hPZeRWxT2Vy7J0wWObLZzvTNh9
#       +trrWc0SPUFaM4uryQ6A8HtoiGD3jqQCueSzB83BBUG6XVm84/88tk06G6FNEgZLEzJmfE
#       1/XNCQ9uhSOhqwyYJIxUqCgRcFLo3ge6R6ukkKRCMDAOi423OOj/hBA6WNDE+BRYWjDCVU
#       d6xB6+SNb9y4N2ElUTdpumd4U5eXXGOQKJhFozS7a2kGvqE0f+Ar7E2zpCy4lnYMMRjym3
#       6lEAWaElI7a19UVVCazioGsn+7aeENfeZrzu0zeab5BrmD91/JNNQa4K0+pwOBqZ4KzYL3
#       AeTDK/0I6jxBIH4JQx6W/8/PdkeilUckEnac0vAuf68pAGSa4op8em7CfaTIRoiwuzUXER
#       zb8uqsOwYV6HYw4JfGAjJFDSixRdTS+pPxYH8DIWj27NxlgdeZpHn4/Ek4roiPqsexUmK4
#       rOypGF7Wz6InEZcmLyzP5VLAj2SReILQT0J9G2hO4DdmvXhSXCWkmmu92hULxoXO2FjWAH
#       M+hAaMYNdRI9CbU5FMOxEQHu4cC/8Y0UQ+3dLUCi4UHjoS/BxOHRhoNsIDea8tVsTAyGGF
#       hK8hl7is5bC+H/3GHlZSL1piLppAbuKZjw4wvAStcNqZQlYSCDAw0ohQVr/HTQAN+0MCDl
#       cl3H5yWrcsFoazwXU33CbGp1ZW8kmZETqc0JkZbozPdoPiJpQMx2Z9cjV/bv5k0PwEtqiC
#       DffhoJW1muZK9NBTNrp34edOtaGxwdqySSvaERJ+SgF1xzPsaTc3Iz3fvF1d5dwisLbniO
#       ibsqQcSTJbd9WiZ+D0WtFW00nTlJoaosIwMN11KSFNzn1AHO3fVBPTdcZm/PCikKoEtSuw
#       aO+P4+mlOlLSPKQ/8tb882XVA4xdEsSq6W8oLh/m88FLgRs7yVI8e5xZO1VwM+QvAfeGKp
#       66g2bNC62UPUCpJCyIB2MKvoP37DAkO2roNZ+N8Knk10SqgjGrjyKRGOJ57mfCqrRbP5qI
#       SldpjxJOwEWgTp0qij3oMATlLzQC6SV/GZEZaKwKfQKLCXOZXFwqa2JvW2cjNqmrXahG7b
#       MSYk9lHZyZsJ8peG90Y/lYM8KHhXK99NCd08UP7E5+ewhXlSkxezoaT93KpT+7PkXhhL0H
#       CFuqgMDnuESqnPcfNydBWgAZkYRyxYmFHYBKMVVraeOjFWuIo8+keg9rdkSOYz/95tAjSO
#       9fjmr6U+9zibHICeLhUijoC7vRY87J3gCDyIehMHqeR3Ig6K1TKurVyfFve04O0E72VJmS
#       NeMUm5fgL6ff2i9r6KgdA0etfVLcRXqzb8fhlf68WDsqahMOG4frQOa5JMTrPUk3lGG25o
#       x9yQknMkpeED27y+ZU+XJdDII=
#       -----END OPENSSH PRIVATE KEY-----
#   name: git-credentials
#   type: Opaque
