apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argo-workflows

resources:
- resources/argo-workflows-v3.4.5.yaml
- resources/argo-server-ingress.yaml

patches:
- overlays/argo-server-sa.yaml
- overlays/workflow-controller-configmap.yaml
- overlays/argo-dex-deploy.yaml

patchesStrategicMerge:
- overlays/argo-cd-rbac-cm.yaml