apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argo-workflows

resources:
- resources/argo-workflows-v3.4.5.yaml

overlays:
- overlays/argo-server-sa.yaml
- workflow-controller-configmap.yaml