apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argo-workflows

resources:
- resources/argo-workflows-v3.4.5.yaml
- resources/argo-server-ingress.yaml
# - overlays/argo-cd-rbac-cm.yaml
- secrets/argo-secrets.yaml
# - overlays/argo-server-sa-readonly.yaml
# - overlays/argo-server-sa-admin.yaml
- templates/test-template.yaml
- templates/pulumi-up.yaml

# bases:
# - templates

patches:
- overlays/argo-server-sa.yaml
- overlays/workflow-controller-configmap.yaml
- overlays/argo-server-deploy.yaml
- overlays/argo-server-role.yaml
- overlays/argo-server-rolebinding.yaml
- overlays/workflow-controller-role.yaml
- overlays/workflow-controller-rolebinding.yaml