name: Helm Chart Deployments
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Action level'     
        required: true
        default: 'apply'
      tags:
        description: 'Apply helm charts'  
jobs:
  apply-helm:
    runs-on: ubuntu-latest
    container: praqma/helmsman:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: home-cloud-lab
      - run: helmsman --apply -f helm/linode/home-cloud-lab.yaml