name: Helm Chart Apply
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Action level'     
        required: true
        default: 'apply'
      tags:
        description: 'Apply helm charts'  
jobs:
  apply-helm:
    runs-on: ubuntu-latest
    container: praqma/helmsman:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          context: "${{ secrets.KUBE_CONTEXT }}"
      - run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx
      - run: helmsman --apply -f helm/linode/home-cloud-lab.yaml