name: Pulumi Up
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Action level'     
        required: true
        default: 'apply'
      tags:
        description: 'Pulumi Up'
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
jobs:
  pulumi-up:
    runs-on: ubuntu-latest
    container: pulumi/pulumi:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo $KUBECONFIG > ~/config
          cd pulumi
          pulumi config set --secret kubernetes:kubeconfig < ~/config
      - run: pip install -r pulumi/linode/requirements.txt
      - run: pulumi up -s ${{ secrets.PULUMI_STACK }} -C pulumi/linode --yes