name: Pulumi Preview
on: [push]
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
jobs:
  pulumi-preview:
    runs-on: ubuntu-latest
    container: pulumi/pulumi:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pip install -r pulumi/linode/requirements.txt
      - run: pulumi preview -s ${{ secrets.PULUMI_STACK }} -C pulumi/linode