name: Pulumi Apply
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Action level'     
        required: true
        default: 'apply'
      tags:
        description: 'Pulumi Apply'
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
jobs:
  pulumi-apply:
    runs-on: ubuntu-latest
    container: pulumi/pulumi:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pip install -r pulumi/linode/requirements.txt
      - run: pulumi apply -s ${{ secrets.PULUMI_STACK }} -C pulumi/linode